### PR TITLE
Fixes in maven projects

### LINKED ISSUE #183: Maven problems on a clean room environment
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Resolving expression: '${final.name}': Detected the following recursive expression cycle in 'final.name': [final.name] @ 
[ERROR] Resolving expression: '${final.name}': Detected the following recursive expression cycle in 'final.name': [final.name] @ 
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-vertx-web:jar is missing. @ line 49, column 21
 @ 
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]   
[ERROR]   The project org.graalvm.tests.integration:quarkus-json:1.0.0-SNAPSHOT (/home/tester/karm/mandrel-integration-tests/apps/quarkus-json/pom.xml) has 2 errors
[ERROR]     Resolving expression: '${final.name}': Detected the following recursive expression cycle in 'final.name': [final.name] -> [Help 2]
[ERROR]     Resolving expression: '${final.name}': Detected the following recursive expression cycle in 'final.name': [final.name] -> [Help 2]
[ERROR]   
[ERROR]   The project org.acme:quarkus-vertx:1.0.0-SNAPSHOT (/home/tester/karm/mandrel-integration-tests/apps/quarkus-vertx/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-vertx-web:jar is missing. @ line 49, column 21

```

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven-3.6.3
Java version: 17.0.8.1, vendor: Eclipse Adoptium, runtime: /opt/jdk-17.0.8.1+1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.14.0-319.el9.aarch64", arch: "aarch64", family: "unix"

```

### PR DESCRIPTION
**Pull request by jerboaa**
In some environments where the maven repository cache is clean you can run into the problems as described in the linked issue.

Closes #183

### CODE REVIEW

**Comment by Karm** [comment]
See https://github.com/Karm/mandrel-integration-tests/issues/183#issuecomment-1711898326

**Comment by Karm** [comment]
The failing test concerns quarkus-vertx and javax/jakarta IMHO.

**Comment by jerboaa** [comment]
> The failing test concerns quarkus-vertx and javax/jakarta IMHO.

Right, not sure why it's failing though. Any ideas?

**Comment by jerboaa** [comment]
> > The failing test concerns quarkus-vertx and javax/jakarta IMHO.
> 
> Right, not sure why it's failing though. Any ideas?

Figured it out. The `quarkus_3.x.patch` no longer applied due to the `pom.xml` changes for `quarkus-vertx`.

**Comment by Karm** [comment]
> > > The failing test concerns quarkus-vertx and javax/jakarta IMHO.
> > 
> > 
> > Right, not sure why it's failing though. Any ideas?
> 
> Figured it out. The `quarkus_3.x.patch` no longer applied due to the `pom.xml` changes for `quarkus-vertx` cleanly. Fixed it. Lets see how it goes.

Thx.

**Pull request merged**
