### PR TITLE
Update to UBI 8.7, update ubi-quarkus-mandrel-builder-image, removes Micronaut

### PR DESCRIPTION
**Pull request by Karm**

### CODE REVIEW

**Comment by jerboaa** [comment]
@Karm the image URL change probably breaks some of the older image based tests. Example:

```
Error response from daemon: manifest for quay.io/quarkus/ubi-quarkus-mandrel-builder-image:20.3-java11 not found: manifest unknown: manifest unknown
```

I think we can remove 20.3 (no longer supported). Same for 22.2. We need to fix `21.3`, though.

**Comment by Karm** [comment]
@jerboaa yeah, I will fix it :+1:

**Comment by Karm** [comment]
@jerboaa WIP, no need to review yet...

**Comment by Karm** [comment]
Rady for review

**Review by zakkak — APPROVED** [review]
LGTM, thanks Karm

**Pull request merged**
