### PR TITLE
Builder image: Ports debug Vertx app to Reactive, bumps Q versions

### LINKED ISSUE #78: The `quarkus-resteasy-mutiny` extension used in the quarkus-vertx app is now deprecated
https://github.com/quarkusio/quarkus/commit/212f0dc240d4619da5616cd7269096a7bde3b3e7 deprecated `quarkus-resteasy-mutiny` and now the integration tests fail with:

```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 282.712 s <<< FAILURE! - in org.graalvm.tests.integration.DebugSymbolsTest
Error:  debugSymbolsQuarkusContainer{TestInfo}  Time elapsed: 282.712 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.DebugSymbolsTest/debugSymbolsQuarkusContainer/build-and-run.log and check these offending lines: 
Warning:  [io.quarkus.resteasy.mutiny.deployment.ResteasyMutinyProcessor] The quarkus-resteasy-mutiny extension is deprecated. Switch to RESTEasy Reactive instead. ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.DebugSymbolsTest.debugSymbolsQuarkusContainer(DebugSymbolsTest.java:280)
```

### LINKED ISSUE #229: Switching Vert.x app to RestEasy Reactive, fails debugging session
I have a patch that ports the Vert.x test app to contemporary Quarkus 3.x suggested API, RestEasy Reactive.

[quarkus_3.x.reactive.patch.txt](https://github.com/Karm/mandrel-integration-tests/files/13486026/quarkus_3.x.reactive.patch.txt)

It fails debugging session:

"Cannot execute this command while the selected thread is running"

```
[ERROR] Failures: 
[ERROR]   DebugSymbolsTest.debugSymbolsQuarkusContainer:396->carryOutGDBSession:501 There were errors in the GDB session. Note that commands in the session might depend on each other. Errors: 
Command 'bt' did not match the expected pattern in time '.*at org/acme/vertx/Fruit.java:48.*'.
Output was:
"bt
""Selected thread is running.
"^error,msg="Selected thread is running."(gdb) , 
Command 'list' did not match the expected pattern in time '.*48.*return client.query\("SELECT id, name FROM fruits ORDER BY name ASC.*'.
Output was:
"list
""1     org/graalvm/compiler/replacements/BoxingSnippets.java: No such file or directory.
"^done(gdb) , 
Command 'c&' did not match the expected pattern in time '.*Continuing.*'.
Output was:
"c&
""Cannot execute this command while the selected thread is running.
"^error,msg="Cannot execute this command while the selected thread is running."(gdb)  ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

### PR DESCRIPTION
**Pull request by Karm**
fixes #78
fixes #229

### CODE REVIEW

**Comment by zakkak** [comment]
There are still some warnings that need to be whitelisted:

```
Warning: The option '-H:-ParseOnce' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:BuildOutputJSONFile=quarkus-json_plus-ParseOnce.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:BuildOutputJSONFile=quarkus-json_minus-ParseOnce.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:+ParseOnce' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future. ==> expected: <true> but was: <false>
```

**Review by zakkak — APPROVED** [review]
LGTM other than the warnings that need whitelisting

**Comment by Karm** [comment]
> There are still some warnings that need to be whitelisted:
> 
> ```
> Warning: The option '-H:-ParseOnce' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
> Warning: The option '-H:BuildOutputJSONFile=quarkus-json_plus-ParseOnce.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
> Warning: The option '-H:BuildOutputJSONFile=quarkus-json_minus-ParseOnce.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
> Warning: The option '-H:+ParseOnce' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future. ==> expected: <true> but was: <false>
> ```

I am wrapping them in unlock...

**Comment by Karm** [comment]
All green, wow :)

**Pull request merged**
