### PR TITLE
Fix Mandrel IT runs with JDK 22-based builds

### LINKED ISSUE #209: Add support for latest GraalVM version
`native-image --version` looks like this for JDK 22 based build:

```
native-image 22 2024-03-19
GraalVM Runtime Environment GraalVM CE 22-dev+15.1 (build 22+15-jvmci-b01)
Substrate VM GraalVM CE 22-dev+15.1 (build 22+15, serial gc)
```

This fails many tests, one basic test would be `AppReproducersTest#versionsParsingMandrel`, which fails with this as follows:

```
2023-10-02 18:58:06.845 INFO  [o.g.t.i.u.v.UsedVersion$MVersion] (runNativeImageVersion) Running command [native-image, --version] to determine Mandrel version used.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.362 s <<< FAILURE! - in org.graalvm.tests.integration.AppReproducersTest
[ERROR] versionsParsingMandrel{TestInfo}  Time elapsed: 0.014 s  <<< ERROR!
java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "version" is null

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AppReproducersTest.versionsParsingMandrel » ExceptionInInitializer
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Native image integration TS 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Native image integration TS ........................ SUCCESS [  0.094 s]
[INFO] testsuite .......................................... FAILURE [  3.620 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.785 s
[INFO] Finished at: 2023-10-02T18:58:07+02:00
[INFO] ------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by jerboaa**
Simple mapping to get a GraalVM version based on the JDK major version. This would defer needing to make a decision whether or not we want to use the `release`/`mandrel.release` files instead.

Closes #209

### CODE REVIEW

**Review by zakkak — COMMENTED** [review]
LGTM as a quick work around but I am not sure we need it, see https://github.com/Karm/mandrel-integration-tests/issues/209#issuecomment-1744512300

**Comment by jerboaa** [comment]
> LGTM as a quick work around but I am not sure we need it, see [#209 (comment)](https://github.com/Karm/mandrel-integration-tests/issues/209#issuecomment-1744512300)

Thanks for the review! I do think we should fix it as I sometimes compare mandrel with GraalVM runs for certain issues.

**Comment by jerboaa** [comment]
@zakkak OK to merge this?

**Comment by jerboaa** [comment]
Thanks!

**Pull request merged**
