### PR TITLE
Allow-list quarkus deprecation warning.

### PR DESCRIPTION
**Pull request by jerboaa**
Until https://github.com/quarkusio/quarkus/issues/37072 is fixed so as to reduce test noise.

Related: #220

### CODE REVIEW

**Comment by jerboaa** [comment]
This also allow-lists the for the JFRPerf test since it re-uses the quarkus microprofile allow-listed lines in its setup.

**Comment by michalvavrik** [comment]
FYI there is approved fix https://github.com/quarkusio/quarkus/pull/37130 (but not merged, so might be worth to wait a day to see how it goes)

**Comment by jerboaa** [comment]
Even better, thanks!

**Comment by jerboaa** [comment]
Fixed with https://github.com/quarkusio/quarkus/issues/37072 instead.

**Pull request closed without merging**
