### PR TITLE
Add reproducer for Version parsing IAE

### PR DESCRIPTION
**Pull request by jerboaa**

### CODE REVIEW

**Comment by Karm** [comment]
@jerboaa  https://github.com/jerboaa/mandrel-integration-tests/pull/1

**Comment by jerboaa** [comment]
Thanks @Karm merged that in.

**Comment by Karm** [comment]
@jerboaa  @zakkak So, I read the issue, and IIUC, this is actually supposed to keep failing until the version parsing logic is changed, right?  Because that is what it does for me...

**Comment by zakkak** [comment]
Correct

**Comment by jerboaa** [comment]
Yes, it will only pass once https://github.com/graalvm/mandrel/issues/218 is fixed.

**Pull request merged**
