### PR TITLE
Adds ImageIO / AWT tests

### PR DESCRIPTION
**Pull request by Karm**
Hello,

This adds a test for some ImageIO/AWT capabilities so as we guard against regressions in the area...

How to run just this one test:

```
 mvn clean verify -Ptestsuite -Dtest=AppReproducersTest#imageioAWTTest
```

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
This seems good. Thanks!

**Comment by zakkak** [comment]
@Karm I tried running this with GraalVM CE 20.3.0 and Mandrel 20.3.0.0.Beta2 and both are failing. Shouldn't Mandrel be working?

I tried with
```
export JAVA_HOME=/opt/jvms/mandrel-java11-20.3.0.0.Beta2
export PATH=$JAVA_HOME/bin:$PATH
mvn -e clean verify -Ptestsuite -Dtest=AppReproducersTest#imageioAWTTest
```

**Comment by Karm** [comment]
> @Karm I tried running this with GraalVM CE 20.3.0 and Mandrel 20.3.0.0.Beta2 and both are failing. Shouldn't Mandrel be working?
> 
> I tried with
> 
> ```
> export JAVA_HOME=/opt/jvms/mandrel-java11-20.3.0.0.Beta2
> export PATH=$JAVA_HOME/bin:$PATH
> mvn -e clean verify -Ptestsuite -Dtest=AppReproducersTest#imageioAWTTest
> ```

@zakkak Hmm, how does it fail? What is the message?

20.3.0.0.Final :heavy_check_mark: 
==========

It passes for me with Mandrel 20.3.0.0.Final:

```
$  export JAVA_HOME=/home/karm/workspaceRH/mandrel-release/mandrel-java11-20.3.0.0.Final/;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}

$ native-image --version
GraalVM Version 20.3.0.0.Final (Mandrel Distribution) (Java Version 11.0.9.1+1)

$ mvn -e clean verify -Ptestsuite -Dtest=AppReproducersTest#imageioAWTTest
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Native image integration TS                                        [pom]
[INFO] testsuite                                                          [jar]
[INFO] 
[INFO] ----------------< org.graalvm.tests.integration:parent >----------------
[INFO] Building Native image integration TS 1.0.0-SNAPSHOT                [1/2]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ parent ---
[INFO] 
[INFO] --------------< org.graalvm.tests.integration:testsuite >---------------
[INFO] Building testsuite 1.0.0-SNAPSHOT                                  [2/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ testsuite ---
[INFO] Deleting /home/karm/workspaceRH/mandrel-integration-tests/testsuite/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testsuite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ testsuite ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:add-test-source (add-integration-test-source-as-test-sources) @ testsuite ---
[INFO] Test Source directory: /home/karm/workspaceRH/mandrel-integration-tests/testsuite/src/it/java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ testsuite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ testsuite ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /home/karm/workspaceRH/mandrel-integration-tests/testsuite/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ testsuite ---
[INFO] Surefire report directory: /home/karm/workspaceRH/mandrel-integration-tests/testsuite/target/surefire-reports
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.graalvm.tests.integration.AppReproducersTest
2021-01-08 12:25:34.245 WARN  [o.g.t.i.u.Commands] (getProperty) Failed to detect any of QUARKUS_NATIVE_CONTAINER_RUNTIME,quarkus.native.container-runtime as env or sys props, defaulting to docker
2021-01-08 12:25:34.258 WARN  [o.g.t.i.u.Commands] (getProperty) Failed to detect any of QUARKUS_NATIVE_BUILDER_IMAGE,quarkus.native.builder-image as env or sys props, defaulting to quay.io/quarkus/ubi-quarkus-mandrel:20.1-java11
2021-01-08 12:25:34.341 INFO  [o.g.t.i.AppReproducersTest] (imageioAWTTest) Testing app: IMAGEIO
2021-01-08 12:27:58.652 INFO  [o.g.t.i.AppReproducersTest] (imageioAWTTest) Running...
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 150.021 s - in org.graalvm.tests.integration.AppReproducersTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ testsuite ---
[INFO] Building jar: /home/karm/workspaceRH/mandrel-integration-tests/testsuite/target/testsuite-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ testsuite ---
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ testsuite ---
[INFO] Failsafe report directory: /home/karm/workspaceRH/mandrel-integration-tests/testsuite/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Native image integration TS 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Native image integration TS ........................ SUCCESS [  0.340 s]
[INFO] testsuite .......................................... SUCCESS [02:38 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:38 min
[INFO] Finished at: 2021-01-08T12:28:04+01:00
[INFO] ------------------------------------------------------------------------
```

20.2.0.0.Final :x: 
==========

Fails as expected:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.graalvm.tests.integration.AppReproducersTest
2021-01-08 12:33:00.345 WARN  [o.g.t.i.u.Commands] (getProperty) Failed to detect any of QUARKUS_NATIVE_CONTAINER_RUNTIME,quarkus.native.container-runtime as env or sys props, defaulting to docker
2021-01-08 12:33:00.357 WARN  [o.g.t.i.u.Commands] (getProperty) Failed to detect any of QUARKUS_NATIVE_BUILDER_IMAGE,quarkus.native.builder-image as env or sys props, defaulting to quay.io/quarkus/ubi-quarkus-mandrel:20.1-java11
2021-01-08 12:33:00.431 INFO  [o.g.t.i.AppReproducersTest] (imageioAWTTest) Testing app: IMAGEIO
2021-01-08 12:35:34.647 INFO  [o.g.t.i.AppReproducersTest] (imageioAWTTest) Running...
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 155.689 s <<< FAILURE! - in org.graalvm.tests.integration.AppReproducersTest
[ERROR] imageioAWTTest{TestInfo}  Time elapsed: 154.35 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
There were errors checking the generated image files, see:
mytest.jpg was not generated.
mytest.gif was not generated.
mytest_toS.png was not generated.
mytest.png was not generated.
mytest_toP.png was not generated.
mytest_toL.png was not generated.
mytest.wbmp was not generated.
mytest_toG.png was not generated.
mytest.tiff was not generated.
mytest.bmp was not generated.
mytest.svg was not generated.
mytest_toC.png was not generated. ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.AppReproducersTest.imageioAWTTest(AppReproducersTest.java:210)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AppReproducersTest.imageioAWTTest:210 There were errors checking the generated image files, see:
mytest.jpg was not generated.
mytest.gif was not generated.
mytest_toS.png was not generated.
mytest.png was not generated.
mytest_toP.png was not generated.
mytest_toL.png was not generated.
mytest.wbmp was not generated.
mytest_toG.png was not generated.
mytest.tiff was not generated.
mytest.bmp was not generated.
mytest.svg was not generated.
mytest_toC.png was not generated. ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
```

**Comment by Karm** [comment]
@zakkak I will setup Github workflow here so as I have immediate feedback on PRs. I was about to connect KarmBot to Jenkins, but let's not burden that instance more than necessary...

**Comment by zakkak** [comment]
# 20.3.0.0.Final :x:

```
export JAVA_HOME=/opt/jvms/mandrel-java11-20.3.0.0.Final 
export GRAALVM_HOME=/opt/jvms/mandrel-java11-20.3.0.0.Final 
export PATH=$JAVA_HOME/bin:$PATH             
mvn -e clean verify -Ptestsuite -Dtest=AppReproducersTest#imageioAWTTest
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Native image integration TS                                        [pom]
[INFO] testsuite                                                          [jar]
[INFO] 
[INFO] ----------------< org.graalvm.tests.integration:parent >----------------
[INFO] Building Native image integration TS 1.0.0-SNAPSHOT                [1/2]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ parent ---
[INFO] 
[INFO] --------------< org.graalvm.tests.integration:testsuite >---------------
[INFO] Building testsuite 1.0.0-SNAPSHOT                                  [2/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ testsuite ---
[INFO] Deleting /home/zakkak/code/mandrel-integration-tests/testsuite/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testsuite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ testsuite ---
[INFO] No sources to compile
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:add-test-source (add-integration-test-source-as-test-sources) @ testsuite ---
[INFO] Test Source directory: /home/zakkak/code/mandrel-integration-tests/testsuite/src/it/java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ testsuite ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/zakkak/code/mandrel-integration-tests/testsuite/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ testsuite ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /home/zakkak/code/mandrel-integration-tests/testsuite/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ testsuite ---
[INFO] Surefire report directory: /home/zakkak/code/mandrel-integration-tests/testsuite/target/surefire-reports
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.graalvm.tests.integration.AppReproducersTest
2021-01-08 17:08:57.924 INFO  [o.g.t.i.AppReproducersTest] (imageioAWTTest) Testing app: IMAGEIO
2021-01-08 17:11:06.461 INFO  [o.g.t.i.AppReproducersTest] (imageioAWTTest) Running...
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 132.439 s <<< FAILURE! - in org.graalvm.tests.integration.AppReproducersTest
[ERROR] imageioAWTTest{TestInfo}  Time elapsed: 130.814 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
There were errors checking the generated image files, see:
mytest.tiff's sha256 hash was ae5dc055d0f27b2a95ce73c5c1c489f72f22ee707a42e1732bcb23adfe5bb29d, expected hash: 7b879c98b55e70a414db6796b76ddcd9c353abb9998bfb2f6b3aa2c1fa6bc81a
mytest.wbmp's sha256 hash was 1b57f631d6052ba73c9101f93c71daa03f8c97d7c0230edb229fa003863319e9, expected hash: d5a9cae953a5d6436def014115254c4d7268f042a97069c07942e1ef9193998b
mytest.png's sha256 hash was f0c512167c02131820946acc74e28eed215d2cc23c4988cb0d31af96f9c057bc, expected hash: 68638780950b392fb5f4fbd93d900d14446c55a91c52afb2adc0cbbeb84508f8
mytest.gif's sha256 hash was 60eb2bb167ebd2c9607e64c50f3a86a7fad49772d6c5e0fa03895d3374c4263d, expected hash: 2e8b712b9e3fe240b9fd1d9ccedd622a63344f94998b9cca6d86baad7bac8e81
mytest.jpg's sha256 hash was d591a719ee8310aa8fb20ec801391d804daf306257aa8dc4ab95c1121e7985dd, expected hash: c427e9377c1ad6e787a5c3bb0096eeca68d4c917254f541aefa92e027c2263e8
mytest.svg's sha256 hash was 5d0ea562f52b3b2883d33d4c1286cc072051e813a3d0614dbbb2499adbdcae83, expected hash: b802d1d7609bb8503e14c7d59e13e554470f892ea3db266b3aaa9fff49aacb77
mytest.bmp's sha256 hash was 3a5ea5fcc4352a6077334e7d00e676b794f13bfff6c60260a452e6e3a9c88b17, expected hash: ec29663c7be2fbebd39be4fcea1ca18e81c2e0f31d92f73b3907c47c9f59aa1e ==> expected: <true> but was: <false>
        at org.graalvm.tests.integration.AppReproducersTest.imageioAWTTest(AppReproducersTest.java:210)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AppReproducersTest.imageioAWTTest:210 There were errors checking the generated image files, see:
mytest.tiff's sha256 hash was ae5dc055d0f27b2a95ce73c5c1c489f72f22ee707a42e1732bcb23adfe5bb29d, expected hash: 7b879c98b55e70a414db6796b76ddcd9c353abb9998bfb2f6b3aa2c1fa6bc81a
mytest.wbmp's sha256 hash was 1b57f631d6052ba73c9101f93c71daa03f8c97d7c0230edb229fa003863319e9, expected hash: d5a9cae953a5d6436def014115254c4d7268f042a97069c07942e1ef9193998b
mytest.png's sha256 hash was f0c512167c02131820946acc74e28eed215d2cc23c4988cb0d31af96f9c057bc, expected hash: 68638780950b392fb5f4fbd93d900d14446c55a91c52afb2adc0cbbeb84508f8
mytest.gif's sha256 hash was 60eb2bb167ebd2c9607e64c50f3a86a7fad49772d6c5e0fa03895d3374c4263d, expected hash: 2e8b712b9e3fe240b9fd1d9ccedd622a63344f94998b9cca6d86baad7bac8e81
mytest.jpg's sha256 hash was d591a719ee8310aa8fb20ec801391d804daf306257aa8dc4ab95c1121e7985dd, expected hash: c427e9377c1ad6e787a5c3bb0096eeca68d4c917254f541aefa92e027c2263e8
mytest.svg's sha256 hash was 5d0ea562f52b3b2883d33d4c1286cc072051e813a3d0614dbbb2499adbdcae83, expected hash: b802d1d7609bb8503e14c7d59e13e554470f892ea3db266b3aaa9fff49aacb77
mytest.bmp's sha256 hash was 3a5ea5fcc4352a6077334e7d00e676b794f13bfff6c60260a452e6e3a9c88b17, expected hash: ec29663c7be2fbebd39be4fcea1ca18e81c2e0f31d92f73b3907c47c9f59aa1e ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Native image integration TS 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Native image integration TS ........................ SUCCESS [  0.246 s]
[INFO] testsuite .......................................... FAILURE [02:19 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:19 min
[INFO] Finished at: 2021-01-08T17:11:09+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by Karm** [comment]
@zakkak That is most interesting. I was under the impression that the algorithms generating those images were stable, producing deterministic results on each machine. No idea why my .png has a different hash than yours .png.

Could you do:
```
$ cd apps/imageio/
$ mvn clean package && java -jar ./target/imageio.jar
```
and send me some of those files?

Thanks.

**Comment by Karm** [comment]
Funny thing that apparently all those conversions of Grace M. Hopper's JPEG 2000 picture to different colour spaces do have identical hashed on yours and mine machine.

It's just those files that were generated with Graphics2D geometry that are different...

**Comment by jerboaa** [comment]
> @Karm I tried running this with GraalVM CE 20.3.0 and Mandrel 20.3.0.0.Beta2 and both are failing. Shouldn't Mandrel be working?
> 
> I tried with
> 
> ```
> export JAVA_HOME=/opt/jvms/mandrel-java11-20.3.0.0.Beta2
> export PATH=$JAVA_HOME/bin:$PATH
> mvn -e clean verify -Ptestsuite -Dtest=AppReproducersTest#imageioAWTTest
> ```

@zakkak Beta2 doesn't have the [jpeg ImageIO fix](https://github.com/graalvm/mandrel/commit/9636ce3db7de70f25a9965cb51a28db17f1ff1b4). Final should have it.

**Comment by Karm** [comment]
Hmm, I run it on an Ubuntu VM and indeed those hashes are different...

```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AppReproducersTest.imageioAWTTest:210 There were errors checking the generated image files, see:
mytest.png's sha256 hash was 86abb75c615577f4907ef4ffcbfc69e529b73f8a10d45745deef2ac08c1fb50d, expected hash: 68638780950b392fb5f4fbd93d900d14446c55a91c52afb2adc0cbbeb84508f8
mytest.gif's sha256 hash was 9f9351272dcbd53c113ecc66b375b13638cc4e28ab7bfa7f838f9b109d20d30a, expected hash: 2e8b712b9e3fe240b9fd1d9ccedd622a63344f94998b9cca6d86baad7bac8e81
mytest.jpg's sha256 hash was 356ff2fab79904f0d06c0307d831bbc68e669543abcbd3b654d87af24d558aae, expected hash: c427e9377c1ad6e787a5c3bb0096eeca68d4c917254f541aefa92e027c2263e8
mytest.svg's sha256 hash was 76485f161c32bbf6373db601f5665b015f83d45c18917fc4dfac070e59758a01, expected hash: b802d1d7609bb8503e14c7d59e13e554470f892ea3db266b3aaa9fff49aacb77
mytest.bmp's sha256 hash was d02cf4b0c29c659fe7e2fd75e8dbbcf5cd1b9aac44f4eecf2cd17619083e84f1, expected hash: ec29663c7be2fbebd39be4fcea1ca18e81c2e0f31d92f73b3907c47c9f59aa1e
mytest.tiff's sha256 hash was 7b7738d796b82737b6cb9690c8aba38f9c417fe8d51d3e577f19b0b1e48ed7c5, expected hash: 7b879c98b55e70a414db6796b76ddcd9c353abb9998bfb2f6b3aa2c1fa6bc81a ==> expected: <true> but was: <false>

```

I didn't know that the output wouldn't be same.   I will check in hexa editor and strip the differences before test....

**Comment by Karm** [comment]
@jerboaa  @zakkak 
I circled back to this one, the difference between various systems is in handling blending, compositing, anti-aliasing when it comes to superposing the font on the picture. Difference marked in yellow:
comparison

It is the same regardless of being run with HotSpot JVM or as a native-image.

### Solution:

I removed the test for hardcoded hashes. The test now compares that the hashes of images generated by HotSpot JVM and native image are the same. For example, when I edited one of the images mid-air, between HotSpot JVM run and native-image run:

#### Expected :heavy_check_mark: 

```
[ERROR] Failures: 
[ERROR]   AppReproducersTest.imageioAWTTest:225 There were errors checking the generated image files, see:
mytest.bmp's sha256 hash was ec29663c7be2fbebd39be4fcea1ca18e81c2e0f31d92f73b3907c47c9f59aa1e, expected hash: ab0617a0cf388f3b8c6bbc3dd1a87c2aae081ec687b434db8ecb387c7d83654e ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
```

Ready for merging IMHO

**Review by jerboaa — APPROVED** [review]
Seems OK to me. Thanks for the update.

**Review by zakkak — APPROVED** [review]
Looks Good. I also tested it locally.
Thanks Karm

**Pull request merged**
