### PR TITLE
Quarkus renaming REST extensions

### LINKED ISSUE #250: org.graalvm.tests.integration.JFRTest.jfrPerfTest fails with latest quarkus main
The JFR perf runner seems to no longer compile with quarkus main:

```
 Error:  Failed to execute goal on project jfr-native-image-performance: Could not resolve dependencies for project org.graalvm.tests.integration:jfr-native-image-performance:jar:1.0.0-SNAPSHOT: Could not find artifact io.quarkus:quarkus-resteasy-reactive:jar:999-SNAPSHOT -> [Help 1]
```

See:
https://github.com/graalvm/mandrel/actions/runs/8289954741/job/22688018133#step:11:13726

I believe there was a change in quarkus main which caused this. If we knew the fix, we could apply a similar one.

/cc @Karm

### PR DESCRIPTION
**Pull request by Karm**
fixes #250

### CODE REVIEW

**Comment by Karm** [comment]
```
Err:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 gdb amd64 10.2-0ubuntu1~20.04~1
  503  Service Unavailable [IP: 185.125.190.80 80]
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gdb/gdb_10.2-0ubuntu1~20.04~1_amd64.deb  503  Service Unavailable [IP: 185.125.190.80 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by jerboaa** [comment]
> ```
> Err:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 gdb amd64 10.2-0ubuntu1~20.04~1
>   503  Service Unavailable [IP: 185.125.190.80 80]
> E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gdb/gdb_10.2-0ubuntu1~20.04~1_amd64.deb  503  Service Unavailable [IP: 185.125.190.80 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> @jerboaa GHA glitching...

Yeah. :-(

Question: What does quarkus main, i.e. 999-SNAPSHOT, amount to in terms of quarkus version? Or in other words, has the main branch been tested with this?

**Comment by Karm** [comment]
> > ```
> > Err:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 gdb amd64 10.2-0ubuntu1~20.04~1
> >   503  Service Unavailable [IP: 185.125.190.80 80]
> > E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gdb/gdb_10.2-0ubuntu1~20.04~1_amd64.deb  503  Service Unavailable [IP: 185.125.190.80 80]
> > E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @jerboaa GHA glitching...
> 
> Yeah. :-(
> 
> Question: What does quarkus main, i.e. 999-SNAPSHOT, amount to in terms of quarkus version? Or in other words, has the main branch been tested with this?


>  999-SNAPSHOT, amount to in terms of quarkus version?

it could mean anything, it's just the main branch build, says nothing about its age. In my case on my laptop with this PR, that is: 9d6f6335c6 built as `$ time ./mvnw -Dquickly -Prelocations`

**Comment by Karm** [comment]
```
 Error:  Failures: 
Error:    PerfCheckTest.testQuarkusFullMicroProfile:506 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel-integration-tests/mandrel-integration-tests/ts/testsuite/target/archived-logs/org.graalvm.tests.integration.PerfCheckTest/testQuarkusFullMicroProfile/build-and-run.log and check these offending lines: 
	at io.quarkus.security.runtime.SecurityIdentityAssociation_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkus.security.runtime.SecurityIdentityAssociation_ClientProxy.getIdentity(Unknown Source)
2024-03-20 21:43:55,439 ERROR [org.jbo.thr.errors] (executor-thread-2) Thread Thread[#56,executor-thread-2,5,main] threw an uncaught exception: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.security.runtime.SecurityIdentityAssociation, id=Qby7zgDOyRL0j3YxdYwwuXFQIeE]
	at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.isAnonymous(Unknown Source) ==> expected: <true> but was: <false>
	```
	
	New failure. Investigating....

**Comment by jerboaa** [comment]
> > 999-SNAPSHOT, amount to in terms of quarkus version?
> 
> it could mean anything, it's just the main branch build, says nothing about its age. In my case on my laptop with this PR, that is: [9d6f6335c6](https://github.com/quarkusio/quarkus/commit/9d6f6335c6) built as `$ time ./mvnw -Dquickly -Prelocations`

So does it apply the new 3.9 patch does it? Otherwise it wouldn't build, right?

**Comment by Karm** [comment]
> > > 999-SNAPSHOT, amount to in terms of quarkus version?
> > 
> > 
> > it could mean anything, it's just the main branch build, says nothing about its age. In my case on my laptop with this PR, that is: [9d6f6335c6](https://github.com/quarkusio/quarkus/commit/9d6f6335c6) built as `$ time ./mvnw -Dquickly -Prelocations`
> 
> So does it apply the new 3.9 patch does it? Otherwise it wouldn't build, right?


> So does it apply the new 3.9 patch does it? Otherwise it wouldn't build, right? 

I used  `-Prelocations` so as it builds even without the patch. That way I collected all failures in the log where the TS spotted WARNING about extension relocation. Then I went app by app adding a patch...

**Comment by jerboaa** [comment]
> > > > 999-SNAPSHOT, amount to in terms of quarkus version?
> > > 
> > > 
> > > it could mean anything, it's just the main branch build, says nothing about its age. In my case on my laptop with this PR, that is: [9d6f6335c6](https://github.com/quarkusio/quarkus/commit/9d6f6335c6) built as `$ time ./mvnw -Dquickly -Prelocations`
> > 
> > 
> > So does it apply the new 3.9 patch does it? Otherwise it wouldn't build, right?
> 
> > So does it apply the new 3.9 patch does it? Otherwise it wouldn't build, right?
> 
> I used `-Prelocations` so as it builds even without the patch. That way I collected all failures in the log where the TS spotted WARNING about extension relocation. Then I went app by app adding a patch...

But that's not what the [CI is using](https://github.com/graalvm/mandrel/actions/runs/8368290810/job/22912431459#step:10:7), right? Please check it builds with quarkus main (without `-Prelocations`) and passes the test. Thanks!

**Comment by Karm** [comment]
> But that's not what the [CI is using](https://github.com/graalvm/mandrel/actions/runs/8368290810/job/22912431459#step:10:7), right?

It indeed ain't, it would not have been failing the way it did otherwise. I merely used it to make the update easier.  

As you can see, I added Q 3.9.0.CR2 to the CI here, so it is going to be easily visible that it works / doesn't work.

I am trying to sort out the failure on GHA now, what is cached glitch and what is actual failure. 

Pls do not merge until it's all green.

**Comment by jerboaa** [comment]
> As you can see, I added Q 3.9.0.CR2 to the CI here, so it is going to be easily visible that it works / doesn't work.

But that doesn't test `main` branch and how 999-SNAPSHOT versions are being handled (in terms of the 3.9.x patch). Hence my ask to test with the main branch as well.

**Comment by Karm** [comment]
Forgot about DebugSymbolsTest.debugSymbolsQuarkusContainer:, fixing...

**Comment by Karm** [comment]
So it's not just Q 3.8.3, it's intermittently Q 3.9 too :-(

```
Error:  Failures: 
Error:    PerfCheckTest.testQuarkusFullMicroProfile:506 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel-integration-tests/mandrel-integration-tests/ts/testsuite/target/archived-logs/org.graalvm.tests.integration.PerfCheckTest/testQuarkusFullMicroProfile/build-and-run.log and check these offending lines: 
	at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.arc$delegate(Unknown Source)
2024-03-21 23:43:10,519 ERROR [org.jbo.thr.errors] (executor-thread-1) Thread Thread[#20,executor-thread-1,5,main] threw an uncaught exception: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.security.runtime.SecurityIdentityProxy, id=U3fuB4yO9MSr82V2xU36xFn98dk]
2024-03-21 23:43:23,967 ERROR [org.jbo.thr.errors] (executor-thread-1) Thread Thread[#20,executor-thread-1,5,main] threw an uncaught exception: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.security.runtime.SecurityIdentityProxy, id=U3fuB4yO9MSr82V2xU36xFn98dk]
2024-03-21 23:43:41,969 ERROR [org.jbo.thr.errors] (executor-thread-3) Thread Thread[#35,executor-thread-3,5,main] threw an uncaught exception: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=io.quarkus.security.runtime.SecurityIdentityProxy, id=U3fuB4yO9MSr82V2xU36xFn98dk]
	at io.quarkus.security.runtime.SecurityIdentityProxy_ClientProxy.isAnonymous(Unknown Source) ==> expected: <true> but was: <false>
[INFO] 
```

I incline towards whitelisting so as we have CI clean and investigating separately.

**Comment by jerboaa** [comment]
> I incline towards whitelisting so as we have CI clean and investigating separately.

+1 and please file an issue to investigate it. Thanks!

**Comment by Karm** [comment]
@jerboaa IMHO ready to merge. 

Ad `io.quarkus.security.runtime.SecurityIdentityAssociation`: I am crafting a Q reproducer project and I can deterministically reproduce it. It requires the combination of MP JWT + REST Client + OpenTelemetry in a single app context. It is *unrelated* to native. As soon as I have the minimal reproducer gift wrapped, I paste it on Quarkus issues. It might be so that /me trying to make it simpler for the test app, mushing together client+server app in a single one does something OT did not expect.

**Comment by Karm** [comment]
@jerboaa  Follow up Q issue: https://github.com/quarkusio/quarkus/issues/39667

(it's possible that it's my fault, but let the Q folks decide....)

**Pull request merged**
